/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms_proyect_expotec;

import java.awt.Color;

/**
 *
 * @author admp1
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        setTitle("Principal");
        this.getContentPane().setBackground(new Color(60,60,60));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        anuncio1 = new forms_proyect_expotec.PanelRound();
        anuncio2 = new forms_proyect_expotec.PanelRound();
        pd1 = new forms_proyect_expotec.PanelRound();
        pd8 = new forms_proyect_expotec.PanelRound();
        pd9 = new forms_proyect_expotec.PanelRound();
        pd2 = new forms_proyect_expotec.PanelRound();
        pd3 = new forms_proyect_expotec.PanelRound();
        pd10 = new forms_proyect_expotec.PanelRound();
        pd11 = new forms_proyect_expotec.PanelRound();
        pd4 = new forms_proyect_expotec.PanelRound();
        pd5 = new forms_proyect_expotec.PanelRound();
        pd12 = new forms_proyect_expotec.PanelRound();
        pd13 = new forms_proyect_expotec.PanelRound();
        pd6 = new forms_proyect_expotec.PanelRound();
        pd7 = new forms_proyect_expotec.PanelRound();
        pd14 = new forms_proyect_expotec.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));

        jPanel5.setBackground(new java.awt.Color(112, 112, 108));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anuncio1.setBackground(new java.awt.Color(255, 255, 255));
        anuncio1.setRoundBottomLeft(50);
        anuncio1.setRoundBottomRight(50);
        anuncio1.setRoundTopLeft(50);
        anuncio1.setRoundTopRight(50);

        javax.swing.GroupLayout anuncio1Layout = new javax.swing.GroupLayout(anuncio1);
        anuncio1.setLayout(anuncio1Layout);
        anuncio1Layout.setHorizontalGroup(
            anuncio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        anuncio1Layout.setVerticalGroup(
            anuncio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel5.add(anuncio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 590, 90));

        anuncio2.setBackground(new java.awt.Color(255, 255, 255));
        anuncio2.setRoundBottomLeft(50);
        anuncio2.setRoundBottomRight(50);
        anuncio2.setRoundTopLeft(50);
        anuncio2.setRoundTopRight(50);

        javax.swing.GroupLayout anuncio2Layout = new javax.swing.GroupLayout(anuncio2);
        anuncio2.setLayout(anuncio2Layout);
        anuncio2Layout.setHorizontalGroup(
            anuncio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        anuncio2Layout.setVerticalGroup(
            anuncio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel5.add(anuncio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 560, 90));

        pd1.setBackground(new java.awt.Color(60, 60, 60));
        pd1.setRoundBottomLeft(50);
        pd1.setRoundBottomRight(50);
        pd1.setRoundTopLeft(50);
        pd1.setRoundTopRight(50);

        javax.swing.GroupLayout pd1Layout = new javax.swing.GroupLayout(pd1);
        pd1.setLayout(pd1Layout);
        pd1Layout.setHorizontalGroup(
            pd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd1Layout.setVerticalGroup(
            pd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 110));

        pd8.setBackground(new java.awt.Color(60, 60, 60));
        pd8.setRoundBottomLeft(50);
        pd8.setRoundBottomRight(50);
        pd8.setRoundTopLeft(50);
        pd8.setRoundTopRight(50);

        javax.swing.GroupLayout pd8Layout = new javax.swing.GroupLayout(pd8);
        pd8.setLayout(pd8Layout);
        pd8Layout.setHorizontalGroup(
            pd8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd8Layout.setVerticalGroup(
            pd8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 140, 110));

        pd9.setBackground(new java.awt.Color(60, 60, 60));
        pd9.setRoundBottomLeft(50);
        pd9.setRoundBottomRight(50);
        pd9.setRoundTopLeft(50);
        pd9.setRoundTopRight(50);

        javax.swing.GroupLayout pd9Layout = new javax.swing.GroupLayout(pd9);
        pd9.setLayout(pd9Layout);
        pd9Layout.setHorizontalGroup(
            pd9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd9Layout.setVerticalGroup(
            pd9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 140, 110));

        pd2.setBackground(new java.awt.Color(60, 60, 60));
        pd2.setRoundBottomLeft(50);
        pd2.setRoundBottomRight(50);
        pd2.setRoundTopLeft(50);
        pd2.setRoundTopRight(50);

        javax.swing.GroupLayout pd2Layout = new javax.swing.GroupLayout(pd2);
        pd2.setLayout(pd2Layout);
        pd2Layout.setHorizontalGroup(
            pd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd2Layout.setVerticalGroup(
            pd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 140, 110));

        pd3.setBackground(new java.awt.Color(60, 60, 60));
        pd3.setRoundBottomLeft(50);
        pd3.setRoundBottomRight(50);
        pd3.setRoundTopLeft(50);
        pd3.setRoundTopRight(50);

        javax.swing.GroupLayout pd3Layout = new javax.swing.GroupLayout(pd3);
        pd3.setLayout(pd3Layout);
        pd3Layout.setHorizontalGroup(
            pd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd3Layout.setVerticalGroup(
            pd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 140, 110));

        pd10.setBackground(new java.awt.Color(60, 60, 60));
        pd10.setRoundBottomLeft(50);
        pd10.setRoundBottomRight(50);
        pd10.setRoundTopLeft(50);
        pd10.setRoundTopRight(50);

        javax.swing.GroupLayout pd10Layout = new javax.swing.GroupLayout(pd10);
        pd10.setLayout(pd10Layout);
        pd10Layout.setHorizontalGroup(
            pd10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd10Layout.setVerticalGroup(
            pd10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 140, 110));

        pd11.setBackground(new java.awt.Color(60, 60, 60));
        pd11.setRoundBottomLeft(50);
        pd11.setRoundBottomRight(50);
        pd11.setRoundTopLeft(50);
        pd11.setRoundTopRight(50);

        javax.swing.GroupLayout pd11Layout = new javax.swing.GroupLayout(pd11);
        pd11.setLayout(pd11Layout);
        pd11Layout.setHorizontalGroup(
            pd11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd11Layout.setVerticalGroup(
            pd11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 140, 110));

        pd4.setBackground(new java.awt.Color(60, 60, 60));
        pd4.setRoundBottomLeft(50);
        pd4.setRoundBottomRight(50);
        pd4.setRoundTopLeft(50);
        pd4.setRoundTopRight(50);

        javax.swing.GroupLayout pd4Layout = new javax.swing.GroupLayout(pd4);
        pd4.setLayout(pd4Layout);
        pd4Layout.setHorizontalGroup(
            pd4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd4Layout.setVerticalGroup(
            pd4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 140, 110));

        pd5.setBackground(new java.awt.Color(60, 60, 60));
        pd5.setRoundBottomLeft(50);
        pd5.setRoundBottomRight(50);
        pd5.setRoundTopLeft(50);
        pd5.setRoundTopRight(50);

        javax.swing.GroupLayout pd5Layout = new javax.swing.GroupLayout(pd5);
        pd5.setLayout(pd5Layout);
        pd5Layout.setHorizontalGroup(
            pd5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd5Layout.setVerticalGroup(
            pd5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 140, 110));

        pd12.setBackground(new java.awt.Color(60, 60, 60));
        pd12.setRoundBottomLeft(50);
        pd12.setRoundBottomRight(50);
        pd12.setRoundTopLeft(50);
        pd12.setRoundTopRight(50);

        javax.swing.GroupLayout pd12Layout = new javax.swing.GroupLayout(pd12);
        pd12.setLayout(pd12Layout);
        pd12Layout.setHorizontalGroup(
            pd12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd12Layout.setVerticalGroup(
            pd12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 140, 110));

        pd13.setBackground(new java.awt.Color(60, 60, 60));
        pd13.setRoundBottomLeft(50);
        pd13.setRoundBottomRight(50);
        pd13.setRoundTopLeft(50);
        pd13.setRoundTopRight(50);

        javax.swing.GroupLayout pd13Layout = new javax.swing.GroupLayout(pd13);
        pd13.setLayout(pd13Layout);
        pd13Layout.setHorizontalGroup(
            pd13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd13Layout.setVerticalGroup(
            pd13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 140, 110));

        pd6.setBackground(new java.awt.Color(60, 60, 60));
        pd6.setRoundBottomLeft(50);
        pd6.setRoundBottomRight(50);
        pd6.setRoundTopLeft(50);
        pd6.setRoundTopRight(50);

        javax.swing.GroupLayout pd6Layout = new javax.swing.GroupLayout(pd6);
        pd6.setLayout(pd6Layout);
        pd6Layout.setHorizontalGroup(
            pd6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd6Layout.setVerticalGroup(
            pd6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 140, 110));

        pd7.setBackground(new java.awt.Color(60, 60, 60));
        pd7.setRoundBottomLeft(50);
        pd7.setRoundBottomRight(50);
        pd7.setRoundTopLeft(50);
        pd7.setRoundTopRight(50);

        javax.swing.GroupLayout pd7Layout = new javax.swing.GroupLayout(pd7);
        pd7.setLayout(pd7Layout);
        pd7Layout.setHorizontalGroup(
            pd7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd7Layout.setVerticalGroup(
            pd7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, 140, 110));

        pd14.setBackground(new java.awt.Color(60, 60, 60));
        pd14.setRoundBottomLeft(50);
        pd14.setRoundBottomRight(50);
        pd14.setRoundTopLeft(50);
        pd14.setRoundTopRight(50);

        javax.swing.GroupLayout pd14Layout = new javax.swing.GroupLayout(pd14);
        pd14.setLayout(pd14Layout);
        pd14Layout.setHorizontalGroup(
            pd14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pd14Layout.setVerticalGroup(
            pd14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel5.add(pd14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, 140, 110));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 29, 27));
        jLabel3.setText("Producto");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 420, 70, 20));

        jLabel8.setBackground(new java.awt.Color(60, 60, 60));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(29, 29, 27));
        jLabel8.setText("Producto");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, 20));

        jLabel9.setBackground(new java.awt.Color(60, 60, 60));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(29, 29, 27));
        jLabel9.setText("Producto");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 70, 20));

        jLabel10.setBackground(new java.awt.Color(60, 60, 60));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(29, 29, 27));
        jLabel10.setText("Producto");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 70, 20));

        jLabel11.setBackground(new java.awt.Color(60, 60, 60));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(29, 29, 27));
        jLabel11.setText("Producto");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 70, 20));

        jLabel12.setBackground(new java.awt.Color(60, 60, 60));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(29, 29, 27));
        jLabel12.setText("Producto");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 70, 20));

        jLabel13.setBackground(new java.awt.Color(60, 60, 60));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 29, 27));
        jLabel13.setText("Producto");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 70, 20));

        jLabel14.setBackground(new java.awt.Color(60, 60, 60));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(29, 29, 27));
        jLabel14.setText("Producto");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 70, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 29, 27));
        jLabel15.setText("Producto");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 70, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(29, 29, 27));
        jLabel16.setText("Producto");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 70, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 29, 27));
        jLabel17.setText("Producto");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 70, 20));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(29, 29, 27));
        jLabel18.setText("Producto");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 70, 20));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(29, 29, 27));
        jLabel19.setText("Producto");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 70, 20));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(29, 29, 27));
        jLabel20.setText("Producto");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 70, 20));

        jPanel1.setBackground(new java.awt.Color(29, 29, 27));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METSHOP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 272, 61));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("informacion");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 110, 30));

        jTextField1.setBackground(new java.awt.Color(60, 60, 60));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("  Buscar por categoría, marca, etc...");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 630, 20));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ayuda");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconito.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/linias.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Corazon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, -1, 41));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captura de pantalla 2025-06-07 2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 120, 60));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registarse.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 120, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Campanita (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 90, -1, 41));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Carrito.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 90, -1, 41));

        jPanel2.setBackground(new java.awt.Color(60, 60, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Marcas");
        jButton13.setBorder(null);
        jButton13.setContentAreaFilled(false);
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 115, -1));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Nuevo");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 115, -1));

        jButton14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Ofertas");
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 115, -1));

        jButton17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Categorias");
        jButton17.setBorder(null);
        jButton17.setContentAreaFilled(false);
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, -10, 115, 42));

        jButton18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Membresías");
        jButton18.setBorder(null);
        jButton18.setContentAreaFilled(false);
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 115, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//DEBEMOS DE HACER QUE VUELVA 
       form2 f2 = new form2();
       f2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        form3 f3 = new form3();
        f3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private forms_proyect_expotec.PanelRound anuncio1;
    private forms_proyect_expotec.PanelRound anuncio2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private forms_proyect_expotec.PanelRound pd1;
    private forms_proyect_expotec.PanelRound pd10;
    private forms_proyect_expotec.PanelRound pd11;
    private forms_proyect_expotec.PanelRound pd12;
    private forms_proyect_expotec.PanelRound pd13;
    private forms_proyect_expotec.PanelRound pd14;
    private forms_proyect_expotec.PanelRound pd2;
    private forms_proyect_expotec.PanelRound pd3;
    private forms_proyect_expotec.PanelRound pd4;
    private forms_proyect_expotec.PanelRound pd5;
    private forms_proyect_expotec.PanelRound pd6;
    private forms_proyect_expotec.PanelRound pd7;
    private forms_proyect_expotec.PanelRound pd8;
    private forms_proyect_expotec.PanelRound pd9;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
